ocr:
  sure_thre: 0.98
  unsure_thre: 0.9
  local_best_window: 2
  supported_langs:
    - 'en'
#    - 'ch'
#    - 'ru'
#    - 'japan'
#    - 'fa'
#    - 'korean'
#    - 'fr'
#    - 'german'

logo_caption:
  model_name: "blip_caption"
  model_type: "base_coco"
  expand_ratio: 1

LLM_model: "gpt-3.5-turbo-16k"

brand_recog:
  temperature: 0
  max_tokens: 10
  sleep_time: 0.5
  prompt_path: "./brand_recognition/prompt.json"
  ask_industry: True
  industry:
    temperature: 0
    max_tokens: 20

brand_valid:
  activate: False
  k: 5
  siamese_thre: 0.7

crp_pred:
  temperature: 0
  max_tokens: 100
  sleep_time: 0.5
  prompt_path: "./selection_model/prompt.json"

rank:
  model_name: "ViT-B/32"
  checkpoint_path: "./checkpoints/epoch4_model.pt"
  max_uis_process: 300
  batch_size: 64
  depth_limit: 1
  driver_sleep_time: 5
  script_timeout: 30
  page_load_timeout: 60
